using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Fabricate;

[Generator]
public sealed class FactoryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Collect all builder declarations
        var builderInfos = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Fabricate.FabricateAttribute`1",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetFactoryEntry(ctx))
            .Where(static entry => entry is not null)
            .Collect();

        // Collect assembly-level FabricateFactory attribute
        var factoryName = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Fabricate.FabricateFactoryAttribute",
                predicate: static (node, _) => node is CompilationUnitSyntax,
                transform: static (ctx, _) => GetFactoryName(ctx))
            .Collect();

        var combined = builderInfos.Combine(factoryName);

        context.RegisterSourceOutput(combined, static (spc, data) =>
        {
            var entries = data.Left;
            var factoryNames = data.Right;

            var validEntries = entries.Where(e => e is not null).ToImmutableArray();
            // Stryker disable once Statement : empty validEntries produces no output in GenerateFactory either
            if (validEntries.Length == 0)
                return;

            var className = factoryNames.IsDefaultOrEmpty || factoryNames[0] is null
                ? "A"
                : factoryNames[0]!;

            GenerateFactory(spc, className, validEntries!);
        });
    }

    private static FactoryEntry? GetFactoryEntry(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol builderSymbol)
            return null;

        var attributeData = context.Attributes.FirstOrDefault();
        if (attributeData?.AttributeClass is not { IsGenericType: true, TypeArguments.Length: 1 } attributeClass)
            return null;

        var targetType = attributeClass.TypeArguments[0] as INamedTypeSymbol;
        if (targetType is null)
            return null;

        var builderNamespace = builderSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : builderSymbol.ContainingNamespace.ToDisplayString();

        return new FactoryEntry(
            builderSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            builderSymbol.Name,
            targetType.Name,
            builderNamespace);
    }

    private static string? GetFactoryName(GeneratorAttributeSyntaxContext context)
    {
        var attributeData = context.Attributes.FirstOrDefault();
        if (attributeData is null)
            return null;

        if (attributeData.ConstructorArguments.Length > 0 &&
            attributeData.ConstructorArguments[0].Value is string name)
        {
            return name;
        }

        return "A";
    }

    private static void GenerateFactory(
        SourceProductionContext context,
        string className,
        ImmutableArray<FactoryEntry?> entries)
    {
        // Group by namespace
        var byNamespace = entries
            .GroupBy(e => e!.Namespace);

        foreach (var group in byNamespace)
        {
            var ns = group.Key;
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            if (ns != null)
            {
                sb.AppendLine($"namespace {ns};");
                sb.AppendLine();
            }

            sb.AppendLine($"public static partial class {className}");
            sb.AppendLine("{");

            foreach (var entry in group)
            {
                sb.AppendLine($"    public static {entry!.BuilderFullName} {entry.TargetTypeName} => new();");
            }

            sb.AppendLine("}");

            var fileName = ns != null
                ? $"{ns}.{className}.g.cs"
                : $"{className}.g.cs";
            context.AddSource(fileName, SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}

internal sealed class FactoryEntry
{
    public string BuilderFullName { get; }
    public string BuilderName { get; }
    public string TargetTypeName { get; }
    public string? Namespace { get; }

    public FactoryEntry(string builderFullName, string builderName, string targetTypeName, string? ns)
    {
        BuilderFullName = builderFullName;
        BuilderName = builderName;
        TargetTypeName = targetTypeName;
        Namespace = ns;
    }
}
