using System.Text;
using FluentAssertions;
using Microsoft.CodeAnalysis;
using Xunit;

namespace Fabricate.Tests;

public class MutationKillingTests
{
    [Fact]
    public void BuilderGenerator_EmitsExactSource_ForSimpleSettableClass()
    {
        var source = """
using Fabricate;

namespace TestApp;

public class Patient
{
    public string Name { get; set; } = "";
    public int Age { get; set; }
}

[Fabricate<Patient>]
public partial class PatientBuilder
{
    private static partial Patient ValidInstance() => new() { Name = "John", Age = 30 };
}
""";

        var generated = GenerateSource(source, "PatientBuilder.g.cs", new BuilderGenerator());

        var expected = BuildExpectedSource(
            "// <auto-generated />",
            "#nullable enable",
            string.Empty,
            "namespace TestApp;",
            string.Empty,
            "partial class PatientBuilder",
            "{",
            "    private static partial global::TestApp.Patient ValidInstance();",
            string.Empty,
            "    private string _name = default!;",
            "    private int _age = default!;",
            string.Empty,
            "    public PatientBuilder()",
            "    {",
            "        var seed = ValidInstance();",
            "        _name = seed.Name;",
            "        _age = seed.Age;",
            "    }",
            string.Empty,
            "    public global::TestApp.Patient Build()",
            "        => new global::TestApp.Patient()",
            "        {",
            "            Name = _name,",
            "            Age = _age,",
            "        };",
            string.Empty,
            "    public static implicit operator global::TestApp.Patient(PatientBuilder builder)",
            "        => builder.Build();",
            string.Empty,
            "    public PatientBuilder WithName(string name)",
            "    {",
            "        _name = name;",
            "        return this;",
            "    }",
            string.Empty,
            "    public PatientBuilder WithAge(int age)",
            "    {",
            "        _age = age;",
            "        return this;",
            "    }",
            string.Empty,
            "}");

        generated.Should().Be(expected);
    }

    [Fact]
    public void BuilderGenerator_EmitsExactSource_ForRecordWithConstructor()
    {
        var source = """
using System;
using Fabricate;

namespace TestApp;

public record Appointment(string DoctorName, DateTime ScheduledAt);

[Fabricate<Appointment>]
public partial class AppointmentBuilder
{
    private static partial Appointment ValidInstance() => new("Dr. Smith", new DateTime(2026, 1, 1));
}
""";

        var generated = GenerateSource(source, "AppointmentBuilder.g.cs", new BuilderGenerator());

        var expected = BuildExpectedSource(
            "// <auto-generated />",
            "#nullable enable",
            string.Empty,
            "namespace TestApp;",
            string.Empty,
            "partial class AppointmentBuilder",
            "{",
            "    private static partial global::TestApp.Appointment ValidInstance();",
            string.Empty,
            "    private string _doctorName = default!;",
            "    private global::System.DateTime _scheduledAt = default!;",
            string.Empty,
            "    public AppointmentBuilder()",
            "    {",
            "        var seed = ValidInstance();",
            "        _doctorName = seed.DoctorName;",
            "        _scheduledAt = seed.ScheduledAt;",
            "    }",
            string.Empty,
            "    public global::TestApp.Appointment Build()",
            "        => new global::TestApp.Appointment(_doctorName, _scheduledAt);",
            string.Empty,
            "    public static implicit operator global::TestApp.Appointment(AppointmentBuilder builder)",
            "        => builder.Build();",
            string.Empty,
            "    public AppointmentBuilder WithDoctorName(string doctorName)",
            "    {",
            "        _doctorName = doctorName;",
            "        return this;",
            "    }",
            string.Empty,
            "    public AppointmentBuilder WithScheduledAt(global::System.DateTime scheduledAt)",
            "    {",
            "        _scheduledAt = scheduledAt;",
            "        return this;",
            "    }",
            string.Empty,
            "}");

        generated.Should().Be(expected);
    }

    [Fact]
    public void BuilderGenerator_EmitsExactSource_ForNullableCollectionAndCustomType()
    {
        var source = """
#nullable enable
using System.Collections.Generic;
using Fabricate;

namespace TestApp;

public class Address
{
    public string Street { get; set; } = "";
}

public class Person
{
    public string Name { get; set; } = "";
    public string? MiddleName { get; set; }
    public List<string> Tags { get; set; } = new();
    public Address HomeAddress { get; set; } = new();
}

[Fabricate<Person>]
public partial class PersonBuilder
{
    private static partial Person ValidInstance() => new()
    {
        Name = "John",
        MiddleName = "Quincy",
        Tags = new List<string> { "friend", "vip" },
        HomeAddress = new Address { Street = "123 Main" }
    };
}
""";

        var generated = GenerateSource(source, "PersonBuilder.g.cs", new BuilderGenerator());

        var expected = BuildExpectedSource(
            "// <auto-generated />",
            "#nullable enable",
            string.Empty,
            "namespace TestApp;",
            string.Empty,
            "partial class PersonBuilder",
            "{",
            "    private static partial global::TestApp.Person ValidInstance();",
            string.Empty,
            "    private string _name = default!;",
            "    private string? _middleName = default!;",
            "    private string[] _tags = default!;",
            "    private global::TestApp.Address _homeAddress = default!;",
            string.Empty,
            "    public PersonBuilder()",
            "    {",
            "        var seed = ValidInstance();",
            "        _name = seed.Name;",
            "        _middleName = seed.MiddleName;",
            "        _tags = System.Linq.Enumerable.ToArray(seed.Tags);",
            "        _homeAddress = seed.HomeAddress;",
            "    }",
            string.Empty,
            "    public global::TestApp.Person Build()",
            "        => new global::TestApp.Person()",
            "        {",
            "            Name = _name,",
            "            MiddleName = _middleName,",
            "            Tags = new global::System.Collections.Generic.List<string>(_tags),",
            "            HomeAddress = _homeAddress,",
            "        };",
            string.Empty,
            "    public static implicit operator global::TestApp.Person(PersonBuilder builder)",
            "        => builder.Build();",
            string.Empty,
            "    public PersonBuilder WithName(string name)",
            "    {",
            "        _name = name;",
            "        return this;",
            "    }",
            string.Empty,
            "    public PersonBuilder WithMiddleName(string? middleName)",
            "    {",
            "        _middleName = middleName;",
            "        return this;",
            "    }",
            string.Empty,
            "    public PersonBuilder WithoutMiddleName()",
            "    {",
            "        _middleName = null;",
            "        return this;",
            "    }",
            string.Empty,
            "    public PersonBuilder WithTags(params string[] tags)",
            "    {",
            "        _tags = tags;",
            "        return this;",
            "    }",
            string.Empty,
            "    public PersonBuilder With(global::TestApp.Address homeAddress)",
            "    {",
            "        _homeAddress = homeAddress;",
            "        return this;",
            "    }",
            string.Empty,
            "}");

        generated.Should().Be(expected);
    }

    [Fact]
    public void FactoryGenerator_EmitsExactSource_ForTwoBuilders()
    {
        var source = """
using System;
using Fabricate;

namespace TestApp;

public class Patient
{
    public string Name { get; set; } = "";
}

public record Appointment(string DoctorName, DateTime ScheduledAt);

[Fabricate<Patient>]
public partial class PatientBuilder
{
    private static partial Patient ValidInstance() => new() { Name = "John" };
}

[Fabricate<Appointment>]
public partial class AppointmentBuilder
{
    private static partial Appointment ValidInstance() => new("Dr. Smith", new DateTime(2026, 1, 1));
}
""";

        var generated = GenerateSource(source, "TestApp.A.g.cs", new BuilderGenerator(), new FactoryGenerator());

        var expected = BuildExpectedSource(
            "// <auto-generated />",
            "#nullable enable",
            string.Empty,
            "namespace TestApp;",
            string.Empty,
            "public static partial class A",
            "{",
            "    public static global::TestApp.PatientBuilder Patient => new();",
            "    public static global::TestApp.AppointmentBuilder Appointment => new();",
            "}");

        generated.Should().Be(expected);
    }

    [Fact]
    public void FactoryGenerator_EmitsExactSource_ForCustomFactoryName()
    {
        var source = """
using Fabricate;

[assembly: FabricateFactory("Create")]

namespace TestApp;

public class Patient
{
    public string Name { get; set; } = "";
}

[Fabricate<Patient>]
public partial class PatientBuilder
{
    private static partial Patient ValidInstance() => new() { Name = "John" };
}
""";

        var generated = GenerateSource(source, "TestApp.Create.g.cs", new BuilderGenerator(), new FactoryGenerator());

        var expected = BuildExpectedSource(
            "// <auto-generated />",
            "#nullable enable",
            string.Empty,
            "namespace TestApp;",
            string.Empty,
            "public static partial class Create",
            "{",
            "    public static global::TestApp.PatientBuilder Patient => new();",
            "}");

        generated.Should().Be(expected);
    }

    [Fact]
    public void DiagnosticDescriptor_FAB001_ExposesExpectedStrings()
    {
        DiagnosticDescriptors.MissingValidInstance.Id.Should().Be("FAB001");
        DiagnosticDescriptors.MissingValidInstance.Title.ToString().Should().Be("Missing ValidInstance implementation");
        DiagnosticDescriptors.MissingValidInstance.MessageFormat.ToString().Should().Be("Builder '{0}' must implement 'static partial {1} ValidInstance()' to provide default values");
        DiagnosticDescriptors.MissingValidInstance.MessageFormat.ToString().Should().Contain("must implement 'static partial {1} ValidInstance()'");
        DiagnosticDescriptors.MissingValidInstance.Category.Should().Be("Fabricate");
    }

    [Fact]
    public void DiagnosticDescriptor_FAB002_ExposesExpectedStrings()
    {
        DiagnosticDescriptors.BuilderNamingSuggestion.Id.Should().Be("FAB002");
        DiagnosticDescriptors.BuilderNamingSuggestion.Title.ToString().Should().Be("Builder class naming suggestion");
        DiagnosticDescriptors.BuilderNamingSuggestion.MessageFormat.ToString().Should().Be("Builder class '{0}' does not end with 'Builder' - consider renaming to '{1}Builder' to avoid namespace conflicts");
        DiagnosticDescriptors.BuilderNamingSuggestion.MessageFormat.ToString().Should().Contain("does not end with 'Builder'");
        DiagnosticDescriptors.BuilderNamingSuggestion.Category.Should().Be("Fabricate");
    }

    [Fact]
    public void DiagnosticDescriptor_FAB003_ExposesExpectedStrings()
    {
        DiagnosticDescriptors.CannotResolveConstructor.Id.Should().Be("FAB003");
        DiagnosticDescriptors.CannotResolveConstructor.Title.ToString().Should().Be("Cannot resolve constructor");
        DiagnosticDescriptors.CannotResolveConstructor.MessageFormat.ToString().Should().Be("Cannot find a suitable constructor for type '{0}' - ensure the type has a public constructor whose parameters can be matched to its properties");
        DiagnosticDescriptors.CannotResolveConstructor.MessageFormat.ToString().Should().Contain("Cannot find a suitable constructor for type '{0}'");
        DiagnosticDescriptors.CannotResolveConstructor.Category.Should().Be("Fabricate");
    }

    [Fact]
    public void DiagnosticDescriptor_FAB004_ExposesExpectedStrings()
    {
        DiagnosticDescriptors.DuplicateFactoryProperty.Id.Should().Be("FAB004");
        DiagnosticDescriptors.DuplicateFactoryProperty.Title.ToString().Should().Be("Duplicate factory property");
        DiagnosticDescriptors.DuplicateFactoryProperty.MessageFormat.ToString().Should().Be("Multiple builders map to factory property '{0}' in class '{1}' - only the first is emitted; target types with distinct simple names or place builders in separate namespaces");
        DiagnosticDescriptors.DuplicateFactoryProperty.MessageFormat.ToString().Should().Contain("only the first is emitted");
        DiagnosticDescriptors.DuplicateFactoryProperty.Category.Should().Be("Fabricate");
    }

    private static string GenerateSource(string source, string fileName, params IIncrementalGenerator[] generators)
    {
        var compilation = TestHarness.CreateCompilation(source);
        var result = TestHarness.RunGenerators(compilation, generators);
        var generatedSources = TestHarness.GetGeneratedSources(result);

        generatedSources.Should().ContainKey(fileName);
        return generatedSources[fileName];
    }

    private static string BuildExpectedSource(params string[] lines)
    {
        var builder = new StringBuilder();
        foreach (var line in lines)
        {
            builder.AppendLine(line);
        }

        return builder.ToString();
    }
}
